### ISSUE TITLE
How do I load an individual bundle?

### ISSUE THREAD

**Issue by kislyuk** [HumanCellAtlas/data-bundle-examples#16]
I was looking in the repo readme for instructions on how to load an individual bundle for testing, however I couldn't find any. Can we add such a section?

P.S. By "load a bundle", I mean download the data files for it and upload the result to the DSS.

**Comment by briandoconnor** [comment]
Sam is working on a loader that uses the files staged on S3 to load into an instance of the blue box.  He will need to comment on the ETA for that (it's a ticket in the current sprint, https://github.com/HumanCellAtlas/data-bundle-examples/issues/9).  @sampierson can comment?  

When Michael and I setup an instance of the blue box for testing and loading sample data on 20170711 we were blocked on the API gateway timeout issue.  So were unable to load all 19K samples.  However, I found a collection of small data bundles that were loadable.  At that time James was able to update the CLI to support creating data bundles by pointing to pre-staged files.  Here's an example of what that looks like.  I believe Sam's plan for his loader is to use the Python bindings instead of the CLI like I did here:

```
# Upload
hca upload --replica aws s3://hca-dss-test-src/data-bundles-examples/import/arrayExpress/E-MTAB-5061/bundles/bundle980/
hca upload --replica aws s3://hca-dss-test-src/data-bundles-examples/import/arrayExpress/E-MTAB-5061/bundles/bundle970/
hca upload --replica aws s3://hca-dss-test-src/data-bundles-examples/import/arrayExpress/E-MTAB-5061/bundles/bundle960/
hca upload --replica aws s3://hca-dss-test-src/data-bundles-examples/import/arrayExpress/E-MTAB-5061/bundles/bundle950/
hca upload --replica aws s3://hca-dss-test-src/data-bundles-examples/import/arrayExpress/E-MTAB-5061/bundles/bundle940/
hca upload --replica aws s3://hca-dss-test-src/data-bundles-examples/import/geo/GSE89232/bundles/bundle930/
hca upload --replica aws s3://hca-dss-test-src/data-bundles-examples/import/geo/GSE89232/bundles/bundle920/
hca upload --replica aws s3://hca-dss-test-src/data-bundles-examples/import/geo/GSE89232/bundles/bundle910/
hca upload --replica aws s3://hca-dss-test-src/data-bundles-examples/import/geo/GSE89232/bundles/bundle900/
hca upload --replica aws s3://hca-dss-test-src/data-bundles-examples/import/geo/GSE89232/bundles/bundle940/
hca upload --replica aws s3://hca-dss-test-src/data-bundles-examples/import/geo/GSE89232/bundles/bundle950/
```

Keep in mind 1) Sam has a new location for these staged files and 2) these staged files need to have the various checksums added as tags.  Both are completed now by Sam.  But hopefully it gives you an idea of how to load a given bundle via James' CLI.

**Comment by sampierson** [comment]
Here is how to stage and store an individual bundle, using the utilities in the data-bundles-examples repository:
```
tar xf import/import.tgz
bin/stager.py --bundle import/geo/GSE75478/bundles/bundle145
bin/storer.py --bundle s3://org-humancellatlas-data-bundle-examples/import/geo/GSE75478/bundles/bundle145
```
